### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by nownabe** [nownabe/moneysaver#2]
* [x] Deploy to Cloud Run
* [x] Store data into Firestore
* [x] Deploy by Terraform
* [x] Add Terraform example
* [x] Add README
